# Do NOT update manually; changes here will be overwritten by Copier
_commit: 0fd2134
_src_path: /opt/odoo-projects/var/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 15.0
org_name: IT-Projects LLC
org_slug: it-projects-llc
rebel_module_groups: []
repo_description: null
repo_name: Odoo Addons for extended access control
repo_slug: access-addons
repo_website: https://github.com/it-projects-llc/access-addons
travis_apt_packages: []
travis_apt_sources: []

